version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  gitlab_ee:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.demo.org'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.demo.org:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8929:8929'
      - '8443:443'
      - '2222:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'

  demo_config:
    image: 'backend-chapter/backend-chapter-demo-config-server'
    hostname: 'config.demo.org'
    ports:
      - '8888:8888'